Update es_ar.json, es_es.json, es_mx.json
minecraftabnormals/The-Endergetic-Expansion pull request #100
Opened 2020-10-04 20:33 UTC by feliclaria

2020-10-04 21:40 UTC, SmellyModder requested changes
Looks good, just some format errors.

2020-10-04 21:40 UTC, SmellyModder commented on src/main/resources/assets/endergetic/lang/es_ar.json
> +  "block.endergetic.ender_torch": "Antorcha de ender",
Incorrectly formatted (continues down a bit), should be aligned with the other lines.

2020-10-04 21:40 UTC, SmellyModder commented on src/main/resources/assets/endergetic/lang/es_es.json
> +  "block.endergetic.ender_torch": "Antorcha de ender",
Incorrectly formatted (continues down a bit), should be aligned with the other lines.

2020-10-04 21:40 UTC, SmellyModder commented on src/main/resources/assets/endergetic/lang/es_mx.json
> +  "block.endergetic.ender_torch": "Antorcha de ender",
Incorrectly formatted (continues down a bit), should be aligned with the other lines.

2020-10-05 10:47 UTC, feliclaria commented
Fixed format

2020-10-05 11:35 UTC, SmellyModder approved these changes

2020-10-05 11:35 UTC, merged